name: Publish to GitHub Pages

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  prep-statements:
    name: prep-statements
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Fetch rdf2rdf
        uses: robinraju/release-downloader@v1.3
        with:
          repository: "architolk/rdf2rdf"
          tag: "v1.1.0"
          fileName: "rdf2rdf.jar"
      - name: concat rdf-files
        run: java -jar rdf2rdf.jar profiles/skos-ap-nl.ttl shapes.nt  &&
             java -jar rdf2rdf.jar concepts/thesaurus.ttl concept.nt
      - name: touch
        run: touch respec/rdf2markdown/statements.nt
      - name: concatenate selected rdf-statements
        run: cat *.nt > statements.nt
      - name: Select rdf-statements
        run: java -jar rdf2rdf.jar statements.nt Begrippenkader-selectedStatements.nt respec/rdf2markdown/queries/Begrippenkader-sortstatements.yml
      - name: Select rdf-statements
        run: java -jar rdf2rdf.jar statements.nt Concept-selectedStatements.nt respec/rdf2markdown/queries/Concept-sortstatements.yml
      - name: Select rdf-statements
        run: java -jar rdf2rdf.jar statements.nt Collection-selectedStatements.nt respec/rdf2markdown/queries/Collectie-sortstatements.yml
      - name: Select rdf-statements
        run: java -jar rdf2rdf.jar statements.nt Bron-selectedStatements.nt respec/rdf2markdown/queries/Bron-sortstatements.yml
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdf2markdown-input
          path: |
            statements.nt
            Begrippenkader-selectedStatements.nt
            Concept-selectedStatements.nt
            Collection-selectedStatements.nt
            Bron-selectedStatements.nt
  rdf2markdown-begrippenkader-table:
    needs: [prep-statements]
    name: rdf2respec-begrippenkader-table
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Fetch rdf2xml
        uses: robinraju/release-downloader@v1.3
        with:
          repository: "architolk/rdf2xml"
          tag: "v1.0.0"
          fileName: "rdf2xml.jar"
      - name: Download rdf2markdown-input
        uses: actions/download-artifact@v3
        with:
          name: rdf2markdown-input
      - name: ttl to xml
        run: java -jar rdf2xml.jar Begrippenkader-selectedStatements.nt selectedStatements.xml respec/rdf2markdown/rdf2xml.xsl
      - name: generate tables
        run: java -jar respec/rdf2markdown/jars/saxon9.jar -s:selectedStatements.xml -o:respec/rdf2markdown/Begrippenkader-table.md -xsl:respec/rdf2markdown/rdf2x-table.xsl
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdf2markdown-begrippenkader-table
          path: respec/rdf2markdown/Begrippenkader-table.md
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdf2markdown-begrippenkader-nts
          path: selectedStatements.xml
  rdf2markdown-concept-table:
    needs: [prep-statements]
    name: rdf2respec-concept-table
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Fetch rdf2xml
        uses: robinraju/release-downloader@v1.3
        with:
          repository: "architolk/rdf2xml"
          tag: "v1.0.0"
          fileName: "rdf2xml.jar"
      - name: Download rdf2markdown-input
        uses: actions/download-artifact@v3
        with:
          name: rdf2markdown-input
      - name: ttl to xml
        run: java -jar rdf2xml.jar Concept-selectedStatements.nt selectedStatements.xml respec/rdf2markdown/rdf2xml.xsl
      - name: generate tables
        run: java -jar respec/rdf2markdown/jars/saxon9.jar -s:selectedStatements.xml -o:respec/rdf2markdown/Concept-table.md -xsl:respec/rdf2markdown/rdf2x-table.xsl
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdf2markdown-concept-table
          path: respec/rdf2markdown/Concept-table.md
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdf2markdown-concept-nts
          path: selectedStatements.xml
  rdf2markdown-collectie-table:
    needs: [prep-statements]
    name: rdf2respec-collectie-table
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Fetch rdf2xml
        uses: robinraju/release-downloader@v1.3
        with:
          repository: "architolk/rdf2xml"
          tag: "v1.0.0"
          fileName: "rdf2xml.jar"
      - name: Download rdf2markdown-input
        uses: actions/download-artifact@v3
        with:
          name: rdf2markdown-input
      - name: ttl to xml
        run: java -jar rdf2xml.jar Collection-selectedStatements.nt selectedStatements.xml respec/rdf2markdown/rdf2xml.xsl
      - name: generate tables
        run: java -jar respec/rdf2markdown/jars/saxon9.jar -s:selectedStatements.xml -o:respec/rdf2markdown/Collection-table.md -xsl:respec/rdf2markdown/rdf2x-table.xsl
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdf2markdown-collectie-table
          path: respec/rdf2markdown/Collection-table.md
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdf2markdown-collectie-nts
          path: selectedStatements.xml
  rdf2markdown-bron-table:
    needs: [prep-statements]
    name: rdf2respec-bron-table
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Fetch rdf2xml
        uses: robinraju/release-downloader@v1.3
        with:
          repository: "architolk/rdf2xml"
          tag: "v1.0.0"
          fileName: "rdf2xml.jar"
      - name: Download rdf2markdown-input
        uses: actions/download-artifact@v3
        with:
          name: rdf2markdown-input
      - name: ttl to xml
        run: java -jar rdf2xml.jar Bron-selectedStatements.nt selectedStatements.xml respec/rdf2markdown/rdf2xml.xsl
      - name: generate tables
        run: java -jar respec/rdf2markdown/jars/saxon9.jar -s:selectedStatements.xml -o:respec/rdf2markdown/Bron-table.md -xsl:respec/rdf2markdown/rdf2x-table.xsl
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdf2markdown-bron-table
          path: respec/rdf2markdown/Bron-table.md
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rdf2markdown-bron-nts
          path: selectedStatements.xml
  main:
    needs: [rdf2markdown-begrippenkader-table, rdf2markdown-concept-table, rdf2markdown-collectie-table, rdf2markdown-bron-table]
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Download rdf2mardown
        uses: actions/download-artifact@v3
        with:
          name: rdf2markdown-begrippenkader-table
          path: respec/rdf2markdown
      - name: Download rdf2mardown
        uses: actions/download-artifact@v3
        with:
          name: rdf2markdown-concept-table
          path: respec/rdf2markdown
      - name: Download rdf2mardown
        uses: actions/download-artifact@v3
        with:
          name: rdf2markdown-collectie-table
          path: respec/rdf2markdown
      - name: Download rdf2mardown
        uses: actions/download-artifact@v3
        with:
          name: rdf2markdown-bron-table
          path: respec/rdf2markdown
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
